name: Preview Deployment

on:
  push:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-preview:
    uses: ./.github/workflows/deploy.yml
      with:
        environment: preproduction
        preview: true
      secrets: inherit

